# frozen_string_literal: true

require_relative "shared_examples/a_debug_event_is_logged"
require_relative "shared_examples/a_fatal_event_is_logged"
require_relative "shared_examples/a_logged_event_with_severity"
require_relative "shared_examples/a_surveiled_event"
require_relative "shared_examples/a_warn_event_is_logged"
require_relative "shared_examples/an_error_event_is_logged"
require_relative "shared_examples/an_info_event_is_logged"
require_relative "shared_examples/an_instrumented_exception_with_severity"
require_relative "shared_examples/an_instrumented_error_exception"
require_relative "shared_examples/an_instrumented_fatal_exception"
