# frozen_string_literal: true

require_relative "shared_examples/an_instrumented_exception_with_severity"
require_relative "shared_examples/an_instrumented_fatal_exception"
require_relative "shared_examples/an_instrumented_error_exception"
